# Generated by Django 4.1.5 on 2023-01-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_feedback_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(default=2, upload_to='photo/team'),
            preserve_default=False,
        ),
    ]
