# Generated by Django 4.1.5 on 2023-01-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_team_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='age',
        ),
    ]
