# Generated by Django 4.1.5 on 2023-01-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_team_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Review',
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='photo/staff'),
        ),
    ]
